[package]
name = "compilers_final_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indent = "0.1.1"
itertools = "0.12.1"
anyhow = "1.0.82"
thiserror = "1.0.59"
